### PR TITLE
Remove deprecated ModMenu Stuff

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
- Removes log warn
- Supports new API:
  - ModMenu API was removed
  - ModMenu clientsideonly was removed
  - ModMenu Parent was changed

### CODE REVIEW

**Comment by shedaniel** [comment]
Not how it works, you are supposed to add badges https://github.com/TerraformersMC/ModMenu/wiki/API

**Comment by DragonEggBedrockBreaking** [comment]
Badges are only for library/deprecated. API and clientsideonly have been removed, and parent is easy to re-do. https://github.com/TerraformersMC/ModMenu/wiki/API#parents

**Comment by shedaniel** [comment]
This is also a library.

**Comment by DragonEggBedrockBreaking** [comment]
Ok, I will add the library badge, give me a few mins.

**Comment by DragonEggBedrockBreaking** [comment]
Done here

**Pull request merged**
