### PR TITLE
Add an Enum config entry

### PR DESCRIPTION
**Pull request by MisterPeModder**
Added an enum config entry and added it to the demo.
Also fixed a bug where `saveConsumer` in `IntegerSliderEntry` and `LongSliderEntry` was never called.

demo

### CODE REVIEW

**Comment by shedaniel** [comment]
Does that enum have to implement the Translatable? Some people are soft depending on Cloth so I think they can have a choice to not implement that.

**Comment by shedaniel** [comment]
I will merge this for now

**Comment by MisterPeModder** [comment]
Fair enough, I could use `toString()` but having a dedicated method guarentees the returned string to be a translation key.

Should I had support for this interface?

**Comment by shedaniel** [comment]
It is okay, I am doing it. Thanks for the pr <3

**Pull request merged**
